### ISSUE TITLE
Thanks you, Few questions

### ISSUE THREAD

**Issue by fcenedes** [cleanenergyexchange/fastapi-zitadel-auth#1]
Hi there,

Thanks for sharing this. we are probably a good number of people re-implementing this with FastAPi and Zitadel all over.
But this is probably a good starter for somebody looking at this. So again thanks !

A couple of remarks, if am not off :

- it doesn't support Opaque token (default in Zitadel), therefore you could include a fall back to the introspection endpoint after checking the presented Bearer doesn't have 3 parts. You could also mention in the readme to set the "Auth Token Type" to JWT instead of Bearer
- Self checking the JWT bearer using the JWKS key is perfectly valid, but you may want to mention that is does't take into account if a user has revoked all his sessions. Maybe a warning to user about the potential risks they may face
- I understand this is a template/sample python code, do you think it would be interesting to develop a starlette/FastApi middleware, so people could integrate this as his, without hurdle in their FastApi projects ? potential fork/inspiration : https://github.com/waza-ari/fastapi-keycloak-middleware

kind regards
Flo

**Comment by davidhuser** [comment]
hi Flo,

Zitadel is also looking at this, and others have replied with [their implementation](https://github.com/zitadel/zitadel/issues/8905#issuecomment-2492414333). There's some momentum which is great!

On your remarks:

* Yes, it currently does not implement the Introspection endpoint, the idea was that in high-volume API there's a penalty since all requests need to call the introspection endpoint. I would support a choice (instead of fallback) so that you could choose for which endpoint you want Introspection vs JWKS.
* Yes it should be noted, see also the [Zitadel docs on opaque vs JWKS](https://zitadel.com/docs/concepts/knowledge/opaque-tokens#use-cases-and-trade-offs)
* It would be very beneficial to have a Python package similar to your keycloak example or the [fastapi-azure-auth](https://github.com/Intility/fastapi-azure-auth) equivalent. A starlette Middleware might be considerable effort, see [Kludex/fastapi-tips](https://github.com/Kludex/fastapi-tips?tab=readme-ov-file#8-implement-a-pure-asgi-middleware-instead-of-basehttpmiddleware), so subclassing from `fastapi.security.base.SecurityBase` and implement its `__call__` method might be enough though.

**Comment by fcenedes** [comment]
Hi David,

Thanks for your answer.

- Ok with the switch instead of automatic fallback. The more option the better. 
- We could also envision an optional local cache with eviction and fixed capacity to optimise things further under heavy load(in rust we use moka.rs, and there is his counterpart in python : https://github.com/deliro/moka-py ). 
- As a side note, the jwks endpoint can be sometime empty, if no connections have been made within a configurable period of time. there is a new api to request the rotation of keys.

**Comment by davidhuser** [comment]
hi @fcenedes take a look at v0.1 impementation as in this repo. 

* We have no introspection fallback just yet (PRs welcome) but set up local JWT validation using a TTLCache.
* We don't have any implementation of key rotation but if you have some details you can open an issue.
* Added a note related to opaque vs JWT tokens in the README.

**Comment by fcenedes** [comment]
Thanks you, and congrats for shipping this !
